apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: assettrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: 192.168.3.236/assettrack/collector:v1
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
