apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: assettrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: 192.168.3.236/assettrack/agent:v1
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
